package com.automation.lac.qa.fanapp.mobile.enums;

import lombok.Getter;

@Getter
public enum ButtonsDescription {
  ACCESSIBLE_TOGGLE("Accessible toggle button"),
  ADD_CARD("Add Card"),
  ADD_CARD_CONTINUE("Add card/Continue"),
  ADD_IDENTITY_PASS("Add identity pass"),
  ADD_PAYMENT_METHOD("add payment method"),
  ADD_TEAMMATE_ACCOUNT("Add Teammate Account"),
  ADD_VEHICLE("Add Vehicle"),
  ADD_YOUR_CARDS_ACCOUNT("Add your cards"),
  ALLOW("Allow"),
  ALLOW_WHILE_USING_APP("Allow While Using App"),
  BACK("Back"),
  CANCEL("Cancel"),
  CHANGE("change"),
  CHECK_AUTOFILL("check autofill"),
  CLEAR_NICKNAME("clear nickname."),
  CLIPPERS_TABS("Clippers Tabs"),
  CONFIRM("Confirm Button"),
  CONFIRM_MY_ACCOUNT("Confirm My Account"),
  CONFIRM_PASSWORD("Confirm Password"),
  CONTINUE("Continue Button"),
  CREATE_ACCOUNT("Create Account"),
  CREATE_AN_ACCOUNT("Create An Account"),
  CREATE_ID_ACCOUNT("Create Intuit Dome Account"),
  CURRENT_SELECTION_DATE("Show year picker"),
  DATE_OF_BIRTH("Input date of birth"),
  DATE_PICKER("DatePicker Year"),
  DECREASE_SEATS("Decrease Seats"),
  DELETE_IN_CONFIRMATION_MODAL("delete button in confirmation modal."),
  DELETE_PAYMENT_METHOD("delete payment method"),
  DELETE_UPDATE_IN_CONFIRMATION_MODAL("delete and update button in confirmation modal."),
  ENABLE_PHONE_BIOMETRICS("enable phone biometrics"),
  EVENT_TABS("Events Tabs"),
  EXPECTED_STATE("Expected state"),
  FIND_TICKETS("Find Tickets"),
  GAME_FACE_ID_REMINDER("Game face id reminder link"),
  GIVE_NICKNAME("give it a nickname"),
  GO_TO_PAY("Go To Pay"),
  HIDE_YEAR_PICKER("Hide year picker"),
  INCREASE_SEATS("Increase Seats"),
  I_HAVE_READ("I have read"),
  I_WILL_DO_LATER("I'll do it later"),
  LIVE_THE_FULL_EXPERIENCE("Live The Full Experience"),
  LOGIN("Login"),
  LOG_IN_CREATE_ACCOUNT("LOG IN/CREATE ACCOUNT"),
  LOG_IN_WITH_ANOTHER_ACCOUNT("Log in with another account"),
  LOG_OUT("Log Out"),
  MENU("Menu"),
  MY_ACCOUNT_SETTINGS("My Account Settings"),
  MY_IDENTITY("My Identity"),
  MY_PAYMENTS("My Payments"),
  MY_PROFILE("My Profile screen"),
  MY_VEHICLES("My Vehicles"),
  NEXT_MONTH("Next Month"),
  PASSWORD_SECURITY("Password & Security"),
  PAYMENT_HISTORY("Payments History"),
  PAYMENT_METHODS_MANAGEMENT("Payment Methods Management"),
  PERSONAL_INFORMATION("Personal Information"),
  PLACE_ORDER("Place Order"),
  POPOVER_DISMISS_CALENDAR("Popover Dismiss Calendar Button"),
  PREVIOUS_MONTH("Previous Month"),
  QR_CODE("Qr Code"),
  REMIND_ME_LATER("Remind me later"),
  SAVE_NICKNAME("save nickname."),
  SEARCH("Search Icon"),
  SET_PASSWORD("Set A Password"),
  SHARE_YOUR_PAYMENT_METHODS("Share your Payment Methods"),
  SHOW_CONFIRM_PASSWORD("Show Confirm Password"),
  SHOW_SET_PASSWORD("Show Set A Password"),
  SING_IN("sing in"),
  SKIP("Skip"),
  STATE_DROPDOWN("State dropdown"),
  SUGGESTED_SEAT("Suggested Seat"),
  SWITCH_CONCERT_FAN("As a concert fan"),
  TAKE_ME_TO_ID("Take Me to Intuit Dome"),
  TEAMMATE_ACCOUNTS("Teammate Accounts"),
  THEME_SWITCH("Theme Switch"),
  TICKETS("Tickets"),
  VERIFY_AGE_REMINDER("Verify Age reminder link"),
  WHILE_USING_APP("While Using The App"),
  YES_LOG_ME_OUT("Yes, Log me out");

  private final String value;

  ButtonsDescription(String value) {
    this.value = value;
  }
}
